---
# file: roles/kafka/tasks/main.yml

- name: Install kafka {{ kafka }}
  ansible.builtin.include_tasks: "install.yml"
  when:
    - action == 'install'

- name: Configure kafka
  ansible.builtin.include_tasks: "config.yml"
  when:
    - action == 'config'


- name: Install kafka connect
  ansible.builtin.include_tasks: "kafka-connect.yml"
  when:
    - action == 'kafka-connect'