---
- name: Create kafka_group
  ansible.builtin.group:
    name: "{{ kafka_group }}"
    state: present

- name: Create kafka_user
  ansible.builtin.user:
    name: "{{ kafka_user }}"
    group: "{{ kafka_group }}"

- name: Check for kafka installation in {{ kafka_install_dir }}
  ansible.builtin.stat:
    path: '{{ kafka_install_dir }}'
  changed_when: false
  register: kafka_binary

- name: Downloading and installing kafka
  when: not kafka_binary.stat.exists
  block:
    - name: Downloading {{ kafka_tgz_url }}
      ansible.builtin.get_url:
        url: '{{ kafka_tgz_url }}'
        dest: '/tmp/{{ kafka_tgz }}'
        validate_certs: false
        mode: '644'
    - name: Unarchive {{ kafka_tgz }}
      ansible.builtin.unarchive:
        remote_src: true
        src: '/tmp/{{ kafka_tgz }}'
        dest: '{{ kafka_install_parent_dir }}'
        owner: '{{ kafka_user }}'
        group: '{{ kafka_group }}'
        creates: '{{ kafka_install_dir }}'
  always:
    - name: Rm {{ kafka_tgz }}
      ansible.builtin.file:
        path: '/tmp/{{ kafka_tgz }}'
        state: absent


- name: Linking {{ kafka_install_link_dir }} to {{ kafka_install_dir }}
  ansible.builtin.file:
    src: '{{ kafka_install_dir }}'
    dest: '{{ kafka_install_link_dir }}'
    owner: '{{ kafka_user }}'
    group: '{{ kafka_group }}'
    state: link

- name: Include kafka scripts in the default path
  ansible.builtin.template:
    src: 'kafka.sh.j2'
    dest: '/etc/profile.d/kafka.sh'
    mode: '644'

- name: Create Kafka config
  ansible.builtin.template:
    src: "server.properties.j2"
    dest: "{{ kafka_install_dir }}/config/kraft/server.properties"
    mode: "644"

- name: Check for kafka data dir
  ansible.builtin.stat:
    path: '{{ kafka_install_dir }}/data'
  changed_when: false
  register: kafka_data

- name: Create data directories and format Log Directories
  when: not kafka_data.stat.exists
  block:
    - name: Create data directories
      ansible.builtin.file:
        path: '{{ kafka_install_dir }}/data'
        owner: "{{ kafka_user }}"
        group: "{{ kafka_group }}"
        state: "directory"
        mode: "0750"
    - name: Format Log Directories
      ansible.builtin.command: "{{ kafka_install_dir }}/bin/kafka-storage.sh format -t {{ kafka_cluster_uuid }} -c {{ kafka_install_dir }}/config/kraft/server.properties"
      register: _result
  always:
    - name: Debug _result
      ansible.builtin.debug:
        var: _result

- name: Create Kafka service
  ansible.builtin.template:
    src: "kafka.service.j2"
    dest: "/etc/systemd/system/kafka.service"
    mode: "644"
  notify:
    - Start and enable service
    - Restart service